//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogZak
    {
        public int id { get; set; }
        public string Logg { get; set; }
        public string Pass { get; set; }
        public int Hos_id { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
