//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodaja
    {
        public int id { get; set; }
        public System.DateTime Data { get; set; }
        public int id_Zakaza { get; set; }
    
        public virtual ZakazList ZakazList { get; set; }
    }
}
